RandomForest:
  n_estimators: 200
  max_depth: 12
  class_weight: {0: 1, 1: 10}  # Give more weight to fraud class
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: "sqrt"
  bootstrap: true
  oob_score: true
  
LogisticRegression:
  C: 1.0
  penalty: "l2"
  solver: "liblinear"
  
IsolationForest:
  n_estimators: 100
  contamination: "auto"